### ISSUE TITLE
EP and MP Upper Limits

### ISSUE THREAD

**Issue by LanceGundersen** [LanceGundersen/navfit2020#2]
I think our command defaults would have to be adjusted a tad in order to compute this or we do some sort of calculator app-wide?

BUPERSINST 1610.10E 06DEC19

![image](https://user-images.githubusercontent.com/8315447/80920418-c6706e80-8d3d-11ea-88ed-eb091f4a551c.png)
![image](https://user-images.githubusercontent.com/8315447/80920432-da1bd500-8d3d-11ea-9e82-d8a2493975a2.png)

**Comment by moondt** [comment]
I think this calculation would occur during the validation step.  The app could provide a validation error if the Reporting Senior's mix of EP/MP/P do not comport with the Upper Limits business rule.
